= Τρόποι Πληρωμής

[options="autowidth,header",cols=",m,"]
|===
|Όνομα|Κωδικός|Τύπος
|Πληρωμή κατά την παραλαβή|PAY_ON_PICKUP|offline
|Κατάθεση σε τραπεζικό λογαριασμό|BANK_DEPOSIT|offline
|Πιστωτική/Χρεωστική κάρτα|CREDIT_CARD|online
|PayPal|PAYPAL|online
|Stripe|STRIPE|online
|===

Για κάθε τρόπο πληρωμής υπάρχει η δυνατότητα να οριστεί μια επιβάρυνση είτε σαν σταθερό ποσό, είτε σαν ποσοστό επί της συνολικής κράτησης.

Για κάθε online τρόπο πληρωμής υπάρχει η δυνατότητα ορισμού ενός ποσοστού, που μπορεί να πληρώσει ο πελάτης σαν προκαταβολή και το υπόλοιπο ποσό θα πληρωθεί κατά την παραλαβή του οχήματος.

== Πληρωμή κατά την παραλαβή

Η πληρωμή θα γίνει κατά την παραλαβή του οχήματος.

Υπάρχει η δυνατότητα ορισμού ενός ποσοστού, που μπορεί να πληρώσει ο πελάτης σαν προκαταβολή μέσω ενός από τους υπόλοιπους online τρόπους πληρωμής, και το υπόλοιπο ποσό θα πληρωθεί κατά την παραλαβή.

== Κατάθεση σε τραπεζικό λογαριασμό

Η πληρωμή θα γίνει με κατάθεση σε τραπεζικό λογαριασμό.

Τα στοιχεία του λογαριασμού μπορούν να προστεθούν στην περιγραφή του τρόπου πληρωμής.

== Πιστωτική/Χρεωστική κάρτα

Η πληρωμή θα γίνει μέσω πιστωτικής/χρεωστικής κάρτας.

Το σύστημα πρέπει να είναι συνδεδεμένο με έναν απο τους τρεις παρόχους.

[[bank-providers]]
.Πάροχοι
[options="autowidth,header", cols="m,"]
|===
|Όνομα|Περιγραφή
|Cardlink|Εξυπηρετεί τις τράπεζες Alpha Bank και Eurobank
|EPay|Εξυπηρετεί την Τράπεζα Πειραιώς
|NBG|Εξυπηρετεί την Εθνική Τράπεζα
|===

== PayPal

Η πληρωμή θα γίνει μέσω της πλατφόρμας του PayPal.

CAUTION: Απαιτείται παραμετροποίηση μέσω της πλατφόρμας.

== Stripe

H πλατφόρμα του Stripe χρησιμοποιείται ηια να καλύψει τις ανάγκες του Apple και Google Pay.

CAUTION: Απαιτείται παραμετροποίηση μέσω της πλατφόρμας και των υπηρεσιών των Apple και Google.

== Πεδία

[options="header", cols="1m,3a"]
|===
|Πεδίο|Περιγραφή
|Όνομα|*(readonly)* Περιγραφικό όνομα του τρόπου πληρωμής.
|Κωδικός|*(readonly)* Ο κωδικός συστήματος του τρόπου πληρωμής.
|Ενεργός|Αν θα είναι ενεργός ή όχι ο τρόπος πληρωμής. Οι ανενεργοί τρόποι πληρωμής δεν είναι διαθέσιμοι στο {app-front}.
|Πάροχος τράπεζας|Ενεργοποιείται μόνο για τον τρόπο πληρωμής με κωδικό `CREDIT_CARD`, για να επιλεγεί xref:bank-providers[η τράπεζα πάροχος] που έχει συνδεθεί με το σύστημα.
|Σειρά|Η σειρά με την οποία θα εμφανίζεται ο τρόπος πληρωμής στο {app-front}.
|Χρέωση|Η επιβάρυνση που έχει ο τρόπος πληρωμής.

[NOTE]
====
Το πεδίο δέχεται μόνο αριθμούς και το σύμβολο %.

Αν ο αριθμός τελειώνει με το σύμβολο % τότε η χρέωση υπολογίζεται σαν ποσοστό επι της συνολικής κράτησης, διαφορετικά σαν σταθερό ποσό.
====
|Προκαταβολή|Το ποσοστό της προκαταβολής που μπορεί να δώσει ο πελάτης. Ενεργοποιείται μόνο για τους τρόπους πληρωμής που υποστηρίζουν προκαταβολή. Αν οριστεί τότε είναι υποχρεωτικό ο πελάτης να δώσει προκαταβολή.
|Περιγραφή|Σύντομη περιγραφή για τον τρόπο πληρωμής ή/και πληροφοριακά στοιχεία, όπως για παράδειγμα η τραπεζικοί λογαριασμοί για πληρωμή με κατάθεση στην τράπεζα.
|===