= Ρυθμίσεις Email

Έχουμε τις κατηγορίες email

* Γενικές
* Φόρμα ενοικίασης
* Φόρμα επικοινωνίας
* Φόρμα προσφοράς

== Γενικές
Ο ρυθμίσεις αυτές εφαρμόζονται αν δεν έχουν οριστεί οι ειδικές ρυθμίσεις των υπόλοιπων κατηγοριών email. Είναι ο εύκολος τρόπος για να ρυθμίσουμε όλα τα email αν δε χρειάζεται η κάθε κατηγορία να έχει τα δικά της.

=== Από
Η διεύθυνση από την οποία θα φαίνεται ότι έχει σταλθεί το email.

=== Προς
Η διεύθυνση που θα λαμβάνει τα email της συγκεκριμένης κατηγορίας.

CAUTION: Δεν έχουμε επιλογές για τα _Θέμα_ και _Αποστολή αντιγράφου_, καθώς η κάθε μια από της υπόλοιπες κατηγορίες έχουν τις επιλογές αυτές με προεπιλεγμένη τιμή.

== Φόρμα ενοικίασης
Τα email που στέλνονται έπειτα από τη διαδικασία της ενοικίασης.

=== Θέμα
Το θέμα του email. Είναι πολυγλωσσικό πεδίο οπότε πρέπει να οριστεί σε όλες τις γλώσσες. Δέχεται σαν παράμετρο (%s) τον κωδικό ενοικίασης. Αν δεν οριστεί τότε υπάρχει προεπιλεγμένη τιμή μόνο για Αγγλικά (en) `New Rental - %s`.

=== Από
Η διεύθυνση από την οποία θα φαίνεται ότι έχει σταλθεί το email.

=== Προς
Η διεύθυνση που θα λαμβάνει τα email της συγκεκριμένης κατηγορίας.

=== Αποστολή αντιγράφου

Αν θα πάρει αντίγραφο του email της ενοικίασης ο πελάτης ή όχι. Προεπιλεγμένη τιμή `Ναι`.

== Φόρμα επικοινωνίας
Τα email που στέλνονται από τη σελίδα επικοινωνίας του site.

=== Θέμα
Το θέμα του email. Είναι πολυγλωσσικό πεδίο οπότε πρέπει να οριστεί σε όλες τις γλώσσες. Δέχεται σαν παράμετρο (%s) το email που έχει συμπληρώσει ο χρήστης στη φόρμα. Αν δεν οριστεί τότε υπάρχει προεπιλεγμένη τιμή μόνο για Αγγλικά (en) `New Contact - %s`.

=== Από
Η διεύθυνση από την οποία θα φαίνεται ότι έχει σταλθεί το email.

=== Προς
Η διεύθυνση που θα λαμβάνει τα email της συγκεκριμένης κατηγορίας.

=== Αποστολή αντιγράφου
Αν θα πάρει αντίγραφο του email της επικοινωνίας ο πελάτης ή όχι. Προεπιλεγμένη τιμή `Όχι`.

== Φόρμα προσφοράς
Τα email που στέλνονται έπειτα από αίτημα του πελάη για να λάβει προσφορά για κάποιο όχημα.

=== Θέμα
Το θέμα του email. Είναι πολυγλωσσικό πεδίο οπότε πρέπει να οριστεί σε όλες τις γλώσσες. Δέχεται σαν παράμετρο (%s) το email που έχει συμπληρώσει ο χρήστης στη φόρμα. Αν δεν οριστεί τότε υπάρχει προεπιλεγμένη τιμή μόνο για Αγγλικά (en) `New Quote - %s`.

=== Από
Η διεύθυνση από την οποία θα φαίνεται ότι έχει σταλθεί το email.

=== Προς
Η διεύθυνση που θα λαμβάνει τα email της συγκεκριμένης κατηγορίας.

=== Αποστολή αντιγράφου
Αν θα πάρει αντίγραφο του email της προσφοράς ο πελάτης ή όχι. Προεπιλεγμένη τιμή `Όχι`.