= Ρυθμίσεις Email

Έχουμε τις κατηγορίες email

* <<#general>>
* <<#rental-form>>
* <<#rental-reminder>>
* <<#rental-thankyou>>
* <<#contact-form>>
* <<#quote-form>>

NOTE: Για το περιεχόμενο των email δείτε την ενότητα xref:technical/reports_email.adoc[].

[[general]]
== Γενικές
Ο ρυθμίσεις αυτές εφαρμόζονται αν δεν έχουν οριστεί οι ειδικές ρυθμίσεις των υπόλοιπων κατηγοριών email. Είναι ο εύκολος τρόπος για να ρυθμίσουμε όλα τα email αν δε χρειάζεται η κάθε κατηγορία να έχει τα δικά της.

=== Από
Η διεύθυνση από την οποία θα φαίνεται ότι έχει σταλθεί το email.

=== Προς
Η διεύθυνση που θα λαμβάνει τα email της συγκεκριμένης κατηγορίας.

CAUTION: Δεν έχουμε επιλογές για τα _Θέμα_ και _Αποστολή αντιγράφου_, καθώς η κάθε μια από της υπόλοιπες κατηγορίες έχουν τις επιλογές αυτές με προεπιλεγμένη τιμή.

[[rental-form]]
== Φόρμα ενοικίασης
Τα email που στέλνονται έπειτα από τη διαδικασία της ενοικίασης.

=== Θέμα
Το θέμα του email. Είναι πολυγλωσσικό πεδίο οπότε πρέπει να οριστεί σε όλες τις γλώσσες. Δέχεται σαν παράμετρο (%s) τον κωδικό ενοικίασης. Αν δεν οριστεί τότε υπάρχει προεπιλεγμένη τιμή μόνο για Αγγλικά (en) `New Rental - %s`.

=== Από
Η διεύθυνση από την οποία θα φαίνεται ότι έχει σταλθεί το email.

=== Προς
Η διεύθυνση που θα λαμβάνει τα email της συγκεκριμένης κατηγορίας.

=== Αποστολή αντιγράφου

Αν θα πάρει αντίγραφο του email της ενοικίασης ο πελάτης ή όχι. Προεπιλεγμένη τιμή `Ναι`.

[[contact-form]]
== Φόρμα επικοινωνίας
Τα email που στέλνονται από τη σελίδα επικοινωνίας του {app-front}.

=== Θέμα
Το θέμα του email. Είναι πολυγλωσσικό πεδίο οπότε πρέπει να οριστεί σε όλες τις γλώσσες. Δέχεται σαν παράμετρο (%s) το email που έχει συμπληρώσει ο χρήστης στη φόρμα. Αν δεν οριστεί τότε υπάρχει προεπιλεγμένη τιμή μόνο για Αγγλικά (en) `New Contact - %s`.

=== Από
Η διεύθυνση από την οποία θα φαίνεται ότι έχει σταλθεί το email.

=== Προς
Η διεύθυνση που θα λαμβάνει τα email της συγκεκριμένης κατηγορίας.

=== Αποστολή αντιγράφου
Αν θα πάρει αντίγραφο του email της επικοινωνίας ο πελάτης ή όχι. Προεπιλεγμένη τιμή `Όχι`.

[[rental-reminder]]
== Reminder ενοικίασης

Τα email που στέλνονται αυτόματα πριν από την παραλαβή του οχήματος.

=== Θέμα
Το θέμα του email είναι πολυγλωσσικό και δέχεται σαν παράμετρο (%s) τον κωδικό ενοικίασης. Αν δεν οριστεί, υπάρχει προεπιλεγμένη τιμή μόνο για Αγγλικά (en) `Rental reminder - %s`.

=== Από
Η διεύθυνση από την οποία θα φαίνεται ότι έχει σταλθεί το reminder.

=== Προς
Η διεύθυνση που θα λαμβάνει το email της κατηγορίας. Αν δεν οριστεί ειδική τιμή, χρησιμοποιούνται τα γενικά πεδία.

=== Αποστολή αντιγράφου
Αν θα λαμβάνει και ο πελάτης αντίγραφο του reminder email.

NOTE: Η λειτουργία ενεργοποιείται από τις xref:admin/settings-system.adoc#rental-reminder-enabled[Ρυθμίσεις Συστήματος].

[[rental-thankyou]]
== Ευχαριστήριο ενοικίασης

Τα email που στέλνονται αυτόματα μετά την ολοκλήρωση της ενοικίασης.

=== Θέμα
Το θέμα του email είναι πολυγλωσσικό και δέχεται σαν παράμετρο (%s) τον κωδικό ενοικίασης. Αν δεν οριστεί, υπάρχει προεπιλεγμένη τιμή μόνο για Αγγλικά (en) `Thank you - %s`.

=== Από
Η διεύθυνση από την οποία θα φαίνεται ότι έχει σταλθεί το thank-you email.

=== Προς
Η διεύθυνση που θα λαμβάνει το email της κατηγορίας. Αν δεν οριστεί ειδική τιμή, χρησιμοποιούνται τα γενικά πεδία.

=== Αποστολή αντιγράφου
Αν θα λαμβάνει και ο πελάτης αντίγραφο του thank-you email.

NOTE: Η λειτουργία ενεργοποιείται από τις xref:admin/settings-system.adoc#rental-thankyou-enabled[Ρυθμίσεις Συστήματος].

[[quote-form]]
== Φόρμα προσφοράς
Τα email που στέλνονται έπειτα από αίτημα του πελάη για να λάβει προσφορά για κάποιο όχημα.

=== Θέμα
Το θέμα του email. Είναι πολυγλωσσικό πεδίο οπότε πρέπει να οριστεί σε όλες τις γλώσσες. Δέχεται σαν παράμετρο (%s) το email που έχει συμπληρώσει ο χρήστης στη φόρμα. Αν δεν οριστεί τότε υπάρχει προεπιλεγμένη τιμή μόνο για Αγγλικά (en) `New Quote - %s`.

=== Από
Η διεύθυνση από την οποία θα φαίνεται ότι έχει σταλθεί το email.

=== Προς
Η διεύθυνση που θα λαμβάνει τα email της συγκεκριμένης κατηγορίας.

=== Αποστολή αντιγράφου
Αν θα πάρει αντίγραφο του email της προσφοράς ο πελάτης ή όχι. Προεπιλεγμένη τιμή `Όχι`.
