= Μοντέλα οχημάτων

Το μοντέλο ενός οχήματος είναι η ονομασία που χρησιμοποιεί ένας κατασκευαστής (μάρκα) για να αναγνωρίσει μια συγκεκριμένη σειρά ή τύπο οχήματος που κατασκευάζει.

Ενώ η μάρκα αναφέρεται στην εταιρεία παραγωγής (π.χ. Toyota, BMW, Ford), το μοντέλο αντιπροσωπεύει έναν συγκεκριμένο τύπο ή κατηγορία οχήματος που παράγεται από αυτή τη μάρκα.

*Παραδείγματα:*

* *Μάρκα:* Toyota +
  *Μοντέλο:* Corolla, Yaris, RAV4
* *Μάρκα:* BMW +
  *Μοντέλο:* 3 Series, X5, Z4
* *Μάρκα:* Ford +
  *Μοντέλο:* Focus, Mustang, Explorer

Το σύστημα έρχεται με προεγκατεστημένα όλα τα βασικά μοντέλα και κατασκευαστές (μάρκες) οχημάτων, αλλά μπορούν να προστεθούν και νέα εφόσον χρειάζεται.

Χρησιμοποιείται κατά τη δημιουργία ενός οχήματος.

== Πεδία Μοντέλων

[options="header", cols="1m,3a"]
|===
|Πεδίο|Περιγραφή
|Όνομα|Το όνομα του μοντέλου π.χ. Corolla
|Μάρκα|Ο κατασκευαστής του μοντέλου. Επιλογή από τη λίστα με τους κατασκευαστές.
|===

== Πεδία Κατασκευαστών

[options="header", cols="1m,3a"]
|===
|Πεδίο|Περιγραφή
|Όνομα|Το όνομα του κατασκευαστή π.χ. Toyota
|===