site:
  title: WheelRent Documentation
  start_page: cr::index.adoc
  robots: allow

git:
  ensure_git_suffix: false

urls:
  html_extension_style: indexify
  latest_version_segment: latest
  latest_version_segment_strategy: redirect:to

content:
  edit_url: false
  sources:
    - url: .
      branches:
        - master
      start_path: docs

ui:
  bundle:
    snapshot: true
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
  supplemental_files: ./supplemental-ui

asciidoc:
  sourcemap: false
  attributes:
    hide-uri-scheme: ~
    icons: font
    page-toctitle: Περιεχόμενα
    note-caption: 'ΣΗΜΕΙΩΣΗ'
    tip-caption: 'ΣΥΜΒΟΥΛΗ'
    important-caption: 'ΣΗΜΑΝΤΙΚΟ'
    caution-caption: 'ΠΡΟΣΟΧΗ'
    warning-caption: 'ΠΡΟΕΙΔΟΠΟΙΗΣΗ'
    sonarqube-appId: 'CarRental_car-rental_be95db4a-452c-44cf-8ca7-85884c65329f'
    sonarqube-token: 'sqb_2ba5f82952764af9f3f2c90100a72eb812907fa2'
  extensions:
    - 'asciidoctor-kroki'
    - '@asciidoctor/tabs'

antora:
  extensions:
    - require: '@antora/atlas-extension'
    - require: '@antora/lunr-extension'
      languages: [en, el]
      index_latest_only: true
