= Κουπόνια

Τα κουπόνια είναι μοναδικοί κωδικοί έκπτωσης που εφαρμόζουν συγκεκριμένο ποσοστό έκπτωσης στο συνολικό κόστος μιας ενοικίασης. Οι πελάτες μπορούν να χρησιμοποιούν τα κουπόνια κατά τη διαδικασία της ενοικίασης, εφόσον διαθέτουν τον μοναδικό κωδικό τους.

*Κάθε κουπόνι έχει τα εξής χαρακτηριστικά:*

Ποσοστό Έκπτωσης:: Καθορίζει το ποσοστό έκπτωσης που εφαρμόζεται στο συνολικό κόστος της κράτησης.
Ημερομηνία Έναρξης και Λήξης Ισχύος:: Το κουπόνι μπορεί να χρησιμοποιηθεί μόνο αν βρίσκεται εντός του χρονικού διαστήματος ισχύος του.
Περίοδος Εφαρμογής Κράτησης:: Μπορεί να οριστεί συγκεκριμένο διάστημα παραλαβής και παράδοσης οχήματος για το οποίο θα ισχύει το κουπόνι. Εάν η κράτηση δεν εμπίπτει σε αυτή την περίοδο, το κουπόνι δεν μπορεί να χρησιμοποιηθεί.
Εφαρμογή σε Ομάδες Οχημάτων:: Το κουπόνι μπορεί να ισχύει είτε για όλα τα διαθέσιμα οχήματα είτε για συγκεκριμένες ομάδες οχημάτων.

== Πεδία

[options="header", cols="1m,3a"]
|===
|Πεδίο|Περιγραφή
|Κωδικός|Ο κωδικός του κουπονιού που δίνεται στον πελάτη προς χρήση. Πρέπει να είναι μοναδικός.

[NOTE]
====
Υπάρχει κανόνας για τους χαρακτήρες που πρέπει να έχει ένας κωδικός κουπονιού.

Πρέπει να είναι έγκυρος σύμφωνα με το regular expression `^[a-zA-Z][a-zA-Z0-9_-]*$`.

* Να αρχίζει με ένα χαρακτήρα του λατινικού αλφαβήτου.
* Να ακολουθείται από χαρακτήρες του λατινικού αλφαβήτου, αριθμούς, καθώς και τους χαρακτήρες παύλα ( - ) και κάτω παύλα ( _ ).
====
|Ποσοστό|Το ποσοστό έκπτωσης που θα εφαρμοστεί.
|Ομάδες οχημάτων|Ορίζουμε τις ομάδες οχημάτων στις οποίες θα έχει ισχύει το κουπόνι. Αν έχουν συμπληρωθεί τότε το κουπόνι θα ισχύει μόνο εφόσον έχει επιλεγεί όχημα που ανήκει σε αυτές τις ομάδες, διαφορετικά θα ισχύει για όλα τα οχήματα.
|Ημ/νία έναρξης|Η ημερομηνία έναρξης ισχύος του κουπονιού.
|Ημ/νία λήξης|Η ημερομηνία λήξης ισχύος του κουπονιού.
|Ημ/νία έναρξης ενοικίασης|Αν οριστεί τότε για να ισχύει το κουπόνι η παραλαβή θα πρέπει να είναι μετά από αυτή την ημερομηνία (>=).
|Ημ/νία λήξης ενοικίασης|Αν οριστεί τότε για να ισχύει το κουπόνι η παράδοση θα πρέπει να είναι πρίν από αυτή την ημερομηνία (\<=).
|Ενεργό|Αν θα είναι ενεργό το κουπόνι ή όχι. Αν δεν είναι ενεργό η έκπτωση δε θα εφαρμοστεί ακόμα και αν δοθεί το κουπόνι κατά την ενοικίαση.
|===
