= Εκπτώσεις

Οι εκπτώσεις είναι μειώσεις του κόστους της βασικής τιμής του οχήματος που παρέχονται στους πελάτες υπό συγκεκριμένες συνθήκες ή κριτήρια. Εφαρμόζονται αυτόματα και ισχύουν για όλα τα οχήματα ή για συγκεκριμένες ομάδες οχημάτων.

Υπάρχουν δύο τύποι εκπτώσεων:

Α. Εκπτώσεις που εφαρμόζονται στο σύνολο της κράτησης::
. *Εκπτώσεις Προαγοράς (Early booking):* Μειώσεις τιμής για πελάτες που κλείνουν την ενοικίαση αρκετό καιρό νωρίτερα.
. *Διάρκεια ενοικίασης (Rental duration):* Μειώσεις τιμής που εφαρμόζονται ανάλογα με το χρονικό διάστημα για το οποίο ένας πελάτης ενοικιάζει ένα όχημα.

Β. Εκπτώσεις που εφαρμόζονται σε κάποιες ημέρες της κράτησης::
. *Προκαθορισμένες Περιόδους (Date Range):* Μειώσεις τιμής που εφαρμόζονται για κρατήσεις που πραγματοποιούνται μέσα σε συγκεκριμένες ημερομηνίες.

Σε μια κράτηση μπορεί να εφαρμοστεί μόνο μια έκπτωση τύπου Α. Εφαρμόζεται αυτή που έχει το μεγαλύτερο ποσοστό έκπτωσης.

Σε μια κράτηση μπορεί να εφαρμοστεί μόνο μια έκπτωση τύπου B για κάθε ημέρα κράτησης. Εφαρμόζεται αυτή που έχει το μεγαλύτερο ποσοστό έκπτωσης.

Αν υπάρχουν 2 εκπτώσεις ίδιου τύπου, μια γενική και μια για ένα συγκεκριμένο γκρουπ, έχει προτεραιότητα αυτή του γκρουπ, ανεξαρτήτως του ποσοστού έκπτωσης.

Μπορούν να εφαρμοστούν περισσότερες από μια εκπτώσεις τύπου B σε μια κράτηση, εφόσον δεν εφαρμόζονται στις ίδιες ημέρες.

.Παράδειγμα εφαρμογής εκπτώσεων τύπου Β
[%autowidth]
|===
3+s|Εκπτώσεις τύπου Β
s|Από s|Έως s|Ποσοστό έκπτωσης&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
|01/04|15/04|10%
|10/04|30/04|5%

3+s|Διάστημα κράτησης
2+s|Από 1+s|Έως
2+|05/04 1+|10/05

3+s|Εφαρμογή εκπτώσεων
s|Από s|Έως s|Ποσοστό έκπτωσης
|05/04|15/04|10%
|16/04|30/04|5%
|01/05|10/05|Χωρίς έκπτωση
|===

<<<

Το συνολικό ποσό της έκπτωσης προκύπτει, υπολογίζοντας την κάθε έκπτωση ξεχωριστά και αθροίζοντας τα ποσά που προκύπτουν.

.Παράδειγμα υπολογισμού των εκπτώσεων
[%autowidth]
|===
s|Έκπτωση Τύπου Α|8% (0.08)
s|Έκπτωση Τύπου Β|10% (0.10) (ισχύει για 2 ημέρες στο διάστημα της κράτησης)
s|Ημέρες κράτησης|10
s|Τιμή ημέρας|20.00€
2+|
s|Ποσό έκπτωσης Α|16.00€ => 20.00 * 0.08 * 10
s|Ποσό έκπτωσης B|4.00€ => 20.00 * 0.10 * 2
s|Συνολικό ποσό έκπτωσης|20.00€ => 16.00(Α) + 4.00(Β)
|===

NOTE: Το ποσοστό έκπτωσης που θα εμφανίζεται στο site (ανάλογα το theme), είναι το ποσοστό που προκύπτει μεταξύ της αρχικής και τελική τιμής, αφού εφαρμοστούν οι εκπτώσεις.

== Πεδία

[options="header", cols="1m,3a"]
|===
|Πεδίο|Περιγραφή
|Όνομα|Αναγνωριστικό της Έκπτωσης.
|Τύπος έκπτωσης|Ο τύπος της έκπτωσης:

* Προαγορά
* Διάρκεια ενοικίασης
* Προκαθορισμένη Περίοδος

|Ποσοστό|Το ποσοστό της έκπτωσης που θα εφαρμοστεί.
|Ομάδες οχημάτων|Ορίζουμε τις ομάδες οχημάτων στις οποίες θα έχει ισχύει η έκπτωση. Αν έχουν συμπληρωθεί τότε η έκπτωση θα ισχύει μόνο εφόσον έχει επιλεγεί όχημα που ανήκει σε αυτές τις ομάδες, διαφορετικά θα ισχύει για όλα τα οχήματα.
|Ενεργή|Αν είναι ενεργή η έκπτωση ή όχι. Αν είναι ανενεργή δε θα εφαρμοστεί από το σύστημα.
2+|
2+s|Τύπος έκπτωσης: Προαγορά
|Μήνες έγκαιρης κράτησης|Πόσους μήνες πριν από την ημερομηνία παραλαβής θεωρείτε η έγκαιρη κράτηση, οπότε και εφαρμόζεται η έκπτωση.
2+s|Τύπος έκπτωσης: Διάρκεια ενοικίασης
|Ελάχιστη διάρκεια|Η ελάχιστη διάρκεια ενοικίασης σε ημέρες για να ισχύσει η έκπτωση.
|Μέγιστη διάρκεια|Η μέγιστη διάρκεια ενοικίασης σε ημέρες για να ισχύσει η έκπτωση.
|Ημ/νία έναρξης|Η ημερομηνία έναρξης ισχύος της έκπτωσης, σε σχέση με την ημερομηνία παραλαβής (προαιρετικά).
|Ημ/νία λήξης|Η ημερομηνία λήξης ισχύος της έκπτωσης, σε σχέση με την ημερομηνία παράδοσης (προαιρετικά).
2+s|Τύπος έκπτωσης: Προκαθορισμένη Περίοδος
|Ημ/νία έναρξης|Η ημερομηνία έναρξης ισχύος της έκπτωσης, σε σχέση με την ημερομηνία παραλαβής.
|Ημ/νία λήξης|Η ημερομηνία λήξης ισχύος της έκπτωσης, σε σχέση με την ημερομηνία παράδοσης.
|===