= Ασφάλειες

Οι ασφάλειες είναι προαιρετικές ή υποχρεωτικές καλύψεις που παρέχονται για να προστατεύσουν τον ενοικιαστή και το όχημα από απρόβλεπτες καταστάσεις κατά τη διάρκεια της μίσθωσης. Αυτές οι καλύψεις μειώνουν ή εξαλείφουν την οικονομική ευθύνη του ενοικιαστή σε περίπτωση ατυχήματος, ζημιάς ή κλοπής του οχήματος.

Επιλέγονται από τον πελάτη κατά τη διάρκεια της διαδικασίας της ενοικίασης στο {app-front}.

Κάθε ασφάλεια έχει ένα σταθερό κόστος, το οποίο μπορεί να υπολογίζεται είτε ανά ημέρα είτε ανά κράτηση. Το κόστος αυτό μπορεί να οριστεί και ανά ομάδα οχημάτων για κάθε ασφάλεια.

Α. Απόλυτο ποσό για κάθε ημέρα κράτησης (Per Day)::
+
.Παράδειγμα υπολογισμού κόστους ασφάλειας τύπου Α.
[%autowidth]
|===
s|Ημέρες κράτησης|10
s|Κόστος ασφάλειας |5.00€ ανά ημέρα
2+|
s|Συνολικό κόστος ασφάλειας|50.00€ => 10 * 5.00&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
|===

Β. Ποσοστό επί του συνόλου της κράτησης (Per Period)::
+
Για τον υπολογισμό του κόστους της ασφάλειας στην περίπτωση λαμβάνουμε υπόψιν
+
* Τη βασική τιμή (πλήθος ημερών * τιμή ημέρας) (ΒΤ)
* Τις εκπτώσεις (Ε)
* Το κόστος έξτρα ωρών (ΚΕΩ)
* Το κόστος νυχτερινών ωρών (ΚΝΝ)
* Ποσοστό της ασφάλειας (ΠΑ)
+
Οπότε το κόστος ασφάλειας προκύπτει ως
+
----
(ΒΤ - Ε + ΚΕΩ + ΚΝΝ) * ΠΑ
----
+
CAUTION: Στο κόστος της ασφάλειας δε συνυπολογίζονται οποιαδήποτε άλλα κόστη, όπως το κόστος της τοποθεσίας παραλαβής/παράδοσης, το κόστος των πρόσθετων, ΦΠΑ, κουπόνια κ.α.
+
.Παράδειγμα υπολογισμού κόστους ασφάλειας τύπου Β.
[%autowidth]
|===
s|Ημέρες κράτησης|10
s|Τιμή ημέρας|20.00€
s|Έκπτωση|10.00€
s|Κόστος έξτρα ωρών|5.00€
s|Κόστος τοποθεσίας παραλαβής|5.00€ (δε συμπεριλαμβάνεται στον υπολογισμό)
s|Ποσοστό ασφάλειας |5% (0.05)
2+|
s|Συνολικό κόστος ασφάλειας|9.75€ => ((10 * 20.00) - 10.00 + 5.00) * 0.05
|===

== Πεδία Ασφάλειας

[options="header", cols="1m,3a"]
|===
|Πεδίο|Περιγραφή
|Τίτλος|Ο τίτλος της ασφάλειας είναι πολυγλωσσικό πεδίο.
|Περιγραφή|Σύντομη περιγραφή για την ασφάλεια.
|Κόστος|Το σταθερό κόστος της ασφάλειας.
|Τύπος Κόστους|Ο τρόπος που θα υπολογίζεται το κόστος της ασφάλειας, *Ανά ημέρα* ή *Ανά κράτηση*
|Σειρά|Η σειρά με την οποία θα εμφανίζεται η ασφάλεια στο {app-front}.
|Κόστος ομάδας οχημάτων|Λίστα με τα διαφορετικά κόστη για την ασφάλεια για συγκεκριμένες ομάδες οχημάτων.
|Ενεργή|Αν θα είναι ενεργή η ασφάλεια ή όχι. Αν δεν είναι ενεργή δε θα είναι διαθέσιμη στο {app-front}.
|===

== Πεδία Κόστους Ομάδας Οχημάτων

[options="header", cols="1m,3a"]
|===
|Πεδίο|Περιγραφή
|Ομάδα οχημάτων|Η ομάδα οχημάτων για την οποία θα ορίσουμε διαφορετικό κόστος για την ασφάλεια.
|Κόστος|Το κόστος που θα έχει η ασφάλεια για τη συγκεκριμένη ομάδα.
|===