= Τοποθεσίες

Οι τοποθεσίες είναι περιοχές που μπορεί να επιλέξει κάποιος για την παραλαβή και παράδοση του οχήματος. Μπορούν να αντιπροσωπεύουν μέρη όπως αεροδρόμια, ξενοδοχεία ή άλλες περιοχές. Οι τοποθεσίες μπορούν να έχουν συγκεκριμένες ρυθμίσεις, όπως να απαιτούν την εισαγωγή αριθμού δωματίου ή πτήσης, να περιλαμβάνουν κόστη παραλαβής/παράδοσης ή να καθορίζουν χρονικά περιθώρια για τις ενοικιάσεις.

*Χρησιμοποιούνται:*

* Στη φόρμα αναζήτησης του {app-front} για να καθορίσουν το σημείο παραλαβής και παράδοσης του οχήματος.
* Όταν ορίζουμε τη μη διαθεσιμότητα μιας ομάδας οχημάτων, για να ορίσουμε αν η ομάδα θα είναι μη διαθέσιμη γενικά ή για συγκεκριμένες τοποθεσίες.
* Όταν ορίζουμε ελάχιστες διάρκειες σε μια σεζόν, για να ορίσουμε αν η ελάχιστη διάρκεια θα ισχύει γενικά ή για συγκεκριμένες τοποθεσίες.
* Στα οχήματα, ώστε στο {app-front} να μπορούμε να δείξουμε επιλεγμένα οχήματα σε συγκεκριμένες τοποθεσίες.

== Πεδία

[options="header", cols="1m,3a"]
|===
|Πεδίο|Περιγραφή
|Τίτλος|Ο τίτλος της τοποθεσίας είναι πολυγλωσσικό πεδίο.
|Κόστος Παραλαβής|Το κόστος παραλαβής του οχήματος από την τοποθεσία.
|Κόστος Παράδοσης|Το κόστος παράδοσης του οχήματος στην τοποθεσία.
|Συντομότερος χρόνος|Το χρονικό περιθώριο μετά το οποίο μπορεί να γίνει κράτηση για τη συγκεκριμένη
τοποθεσία.
|Ομάδα|Χρησιμοποιείται ανάλογα το theme, για να δείξει ομαδοποιημένες τις τοποθεσίες στη φόρμα αναζήτησης.
|Τοποθεσία Google|Συνδέουμε την τοποθεσία με μια τοποθεσία Google, ώστε να μπορούμε να δείξουμε στο {app-front} πληροφορίες για την τοποθεσία αυτή.
|Είναι Ξενοδοχείο|Ορίζει αν η τοποθεσία είναι ξενοδοχείο ή όχι. Αν είναι τότε το αντίστοιχο πεδίο στη φόρμα ενοικίασης είναι υποχρεωτικό.
|Είναι Αεροδρόμιο|Ορίζει αν η τοποθεσία είναι αεροδρόμιο ή όχι. Αν είναι τότε το αντίστοιχο πεδίο στη φόρμα ενοικίασης είναι υποχρεωτικό.
|Προεπιλογή|Αν οριστεί σαν προεπιλογή τότε αυτή η τοποθεσία θα είναι επιλεγμένη εξ αρχής στη φόρμα αναζήτησης. Μόνο μια τοποθεσία μπορεί να οριστεί σαν προεπιλογή.
|Ενεργή|Ορίζει αν η τοποθεσία είναι ενεργή ή όχι. Οι ανενεργές δε θα εμφανίζονται στη λίστα της φόρμας αναζήτησης.
|===
