= Σεζόν

Οι Σεζόν είναι χρονικές περίοδοι, ανεξάρτητες από το έτος, που συνδυάζονται με τις ομάδες οχημάτων για τον καθορισμό του κόστους κράτησης. Επίσης, μπορούμε να ορίσουμε ελάχιστες διάρκειες κράτησης για μια σεζόν, όπου αυτές θα είναι γενικά για τη σεζόν ή για συγκεκριμένες τοποθεσίες.

CAUTION: Οι περίοδοι αυτές πρέπει να καλύπτουν ολόκληρο το ημερολογιακό έτος, ώστε να μην υπάρχουν κενά διαστήματα όπου η χρέωση δεν είναι δυνατή.

== Πεδία

[options="header", cols="1m,3a"]
|===
|Πεδίο|Περιγραφή
|Όνομα|Αναγνωριστικό της Σεζον.
|Ημ/νία έναρξης|Η ημερομηνία έναρξης της περιόδου.
|Ημ/νία λήξης|Η ημερομηνία λήξης της περιόδου.
|Ελάχιστες διάρκειες|Λίστα με τις ελάχιστες διάρκειες που έχουν οριστεί στην περίοδο.
|===

== Πεδία Ελάχιστης Διάρκειας Κράτησης (ΕΔΚ)
[options="header", cols="1m,3a"]
|===
|Πεδίο|Περιγραφή
|Ημέρες|Πόσες ημέρες είναι η ΕΔΚ για αυτή την περίοδο.
|Τοποθεσίες|Σε ποιες τοποθεσίες θα εφαρμοστεί η ΕΔΚ για αυτή την περίοδο. Αν δεν οριστούν τοποθεσίες τότε αυτή η ΕΔΚ εφαρμόζεται γενικά σε όλη την περίοδο.
|===

NOTE: Υπάρχει και η xref:admin/settings-system.adoc#min-duration[ρύθμιση συστήματος] όπου μπορούμε να ορίσουμε ΕΔΚ γενικά για όλο το σύστημα αν δεν οριστεί μέσα από τις Σεζόν.