= Καλώς Ήρθατε
:navtitle: Αρχική

== Τι νέο υπάρχει στη 1.1

Η έκδοση `1.1` εμπλουτίζει την τεκμηρίωση του `nmecar` με νέα ενότητα για το reporting και με πιο καθαρή περιγραφή βασικών λειτουργιών του συστήματος.

Σημεία που ξεχωρίζουν:

* το dashboard xref:reporting/lite-dashboard.adoc[Σύνοψη Επιχείρησης LITE],
* εμπλουτισμένη τεκμηρίωση για χρεώσεις ηλικίας οδηγού,
* εμπλουτισμένη τεκμηρίωση για extras ανά ομάδα οχημάτων,
* πιο πλήρης περιγραφή για reminder / thank-you emails,
* πιο σαφής ροή για πληρωμές `BANK_DEPOSIT`.

Για τη συνοπτική παρουσίαση της έκδοσης δείτε και τη σελίδα xref:release-notes/1.1.adoc[Τι νέο υπάρχει στη 1.1].


Η παρούσα τεκμηρίωση περιγράφει το `nmecar` στη γραμμή έκδοσης `1.1`, με έμφαση στις λειτουργικές δυνατότητες του συστήματος, στη διαχείριση από το backoffice και στη νέα ενότητα reporting.

Για γρήγορη μετάβαση:

* xref:release-notes/1.1.adoc[Τι νέο υπάρχει στη 1.1]
* xref:reporting/index.adoc[Reporting και Dashboards]
* xref:technical/dashboard.adoc[Ρύθμιση σύνδεσης με dashboard]

include::partial$nav_main.adoc[]
