= Τρόποι Πληρωμής

[options="autowidth,header"]
|===
|Όνομα|Κωδικός|Τύπος
|Πληρωμή κατά την παραλαβή|PAY_ON_PICKUP|offline
|Κατάθεση σε τραπεζικό λογαριασμό|BANK_DEPOSIT|offline
|Πιστωτική/Χρεωστική κάρτα|CREDIT_CARD|online
|PayPal|PAYPAL|online
|Stripe|STRIPE|online
|===

Για κάθε τρόπο πληρωμής υπάρχει η δυνατότητα να οριστεί μια επιβάρυνση είτε σαν fixed ποσό, είτε σαν ποσοστό επί της συνολικής κράτησης.

Για κάθε online τρόπο πληρωμής υπάρχει η δυνατότητα ορισμού ενός ποσοστού, που μπορεί να πληρώσει ο πελάτης σαν προκαταβολή και το υπόλοιπο ποσό θα πληρωθεί κατά την παραλαβή του οχήματος. Αυτή την προκαταβολή μπορεί να είναι υποχρεωτική ή όχι.

== Πληρωμή κατά την παραλαβή

Η πληρωμή θα γίνει κατά την παραλαβή του οχήματος.

Υπάρχει η δυνατότητα ορισμού ενός ποσοστού, που μπορεί να πληρώσει ο πελάτης σαν προκαταβολή (υποχρεωτικά ή όχι) μέσω ενός από τους υπόλοιπους online τρόπους πληρωμής, και το υπόλοιπο ποσό θα πληρωθεί κατά την παραλαβή.

== Κατάθεση σε τραπεζικό λογαριασμό

Η πληρωμή θα γίνει με κατάθεση σε τραπεζικό λογαριασμό.

Τα στοιχεία του λογαριασμού μπορούν να προστεθούν στην περιγραφή του τρόπου πληρωμής.

== Πιστωτική/Χρεωστική κάρτα

Η πληρωμή θα γίνει μέσω πιστωτικής/χρεωστικής κάρτας.

Το σύστημα πρέπει να είναι συνδεδεμένο με έναν απο τους τρεις παρόχους.

.Πάροχοι
[options="autowidth,header", cols="s,"]
|===
|Όνομα|Περιγραφή
|Cardlink|Εξυπηρετεί τις τράπεζες Alpha Bank και Eurobank
|EPay|Εξυπηρετεί την Τράπεζα Πειραιώς
|NBG|Εξυπηρετεί την Εθνική Τράπεζα
|===

== PayPal

Η πληρωμή θα γίνει μέσω της πλατφόρμας του PayPal.

CAUTION: Απαιτείται παραμετροποίηση μέσω της πλατφόρμας.

== Stripe

H πλατφόρμα του Stripe χρησιμοποιείται ηια να καλύψει τις ανάγκες του Apple και Google Pay.

CAUTION: Απαιτείται παραμετροποίηση μέσω της πλατφόρμας και των υπηρεσιών των Apple και Google.