= Ρυθμίσεις Mail
:navtitle: Mail

Έχουμε τις κατηγορίες mail

* Γενικές
* Φόρμα ενοικίασης
* Φόρμα επικοινωνίας
* Φόρμα προσφοράς

== Γενικές
Ο ρυθμίσεις αυτές εφαρμόζονται αν δεν έχουν οριστεί οι ειδικές ρυθμίσεις των υπόλοιπων κατηγοριών mail. Είναι ο εύκολος τρόπος για να ρυθμίσουμε όλα τα mail αν δε χρειάζεται η κάθε κατηγορία να έχει τα δικά της.

=== Από
Το email από το οποίο θα φαίνεται ότι έχει σταλθεί το mail.

=== Προς
Το email που θα λαμβάνει τα mail της συγκεκριμένης κατηγορίας.

CAUTION: Δεν έχουμε επιλογή 'Αποστολής αντιγράφου', καθώς η κάθε μια από της υπόλοιπες κατηγορίες έχουν την επιλογή αυτή με προεπιλεγμένη τιμή.

== Φόρμα ενοικίασης
Τα mail που στέλνονται έπειτα από τη διαδικασία της ενοικίασης.

=== Από
Το email από το οποίο θα φαίνεται ότι έχει σταλθεί το mail.

=== Προς
Το email που θα λαμβάνει τα mail της συγκεκριμένης κατηγορίας.

=== Αποστολή αντιγράφου

Αν θα πάρει αντίγραφο του mail της ενοικίασης ο πελάτης ή όχι. Προεπιλεγμένη τιμή `Ναι`.

== Φόρμα επικοινωνίας
Τα mail που στέλνονται από τη σελίδα επικοινωνίας του site.

=== Από
Το email από το οποίο θα φαίνεται ότι έχει σταλθεί το mail.

=== Προς
Το email που θα λαμβάνει τα mail της συγκεκριμένης κατηγορίας.

=== Αποστολή αντιγράφου
Αν θα πάρει αντίγραφο του mail της επικοινωνίας ο πελάτης ή όχι. Προεπιλεγμένη τιμή `Όχι`.

== Φόρμα προσφοράς
Τα mail που στέλνονται έπειτα από αίτημα του πελάη για να λάβει προσφορά για κάποιο όχημα.

=== Από
Το email από το οποίο θα φαίνεται ότι έχει σταλθεί το mail.

=== Προς
Το email που θα λαμβάνει τα mail της συγκεκριμένης κατηγορίας.

=== Αποστολή αντιγράφου
Αν θα πάρει αντίγραφο του mail της προσφοράς ο πελάτης ή όχι. Προεπιλεγμένη τιμή `Όχι`.