= Ρυθμίσεις E-Mails
:navtitle: E-Mails

Έχουμε τις κατηγορίες e-mail

* Γενικές
* Φόρμα ενοικίασης
* Φόρμα επικοινωνίας
* Φόρμα προσφοράς

== Γενικές
Ο ρυθμίσεις αυτές εφαρμόζονται αν δεν έχουν οριστεί οι ειδικές ρυθμίσεις των υπόλοιπων κατηγοριών e-mail. Είναι ο εύκολος τρόπος για να ρυθμίσουμε όλα τα e-mail αν δε χρειάζεται η κάθε κατηγορία να έχει τα δικά της.

=== Από
Η διεύθυνση από την οποία θα φαίνεται ότι έχει σταλθεί το e-mail.

=== Προς
Η διεύθυνση που θα λαμβάνει τα e-mail της συγκεκριμένης κατηγορίας.

CAUTION: Δεν έχουμε επιλογές για τα _Θέμα_ και _Αποστολή αντιγράφου_, καθώς η κάθε μια από της υπόλοιπες κατηγορίες έχουν τις επιλογές αυτές με προεπιλεγμένη τιμή.

== Φόρμα ενοικίασης
Τα e-mails που στέλνονται έπειτα από τη διαδικασία της ενοικίασης.

=== Θέμα
Το θέμα του e-mail. Είναι πολυγλωσσικό πεδίο οπότε πρέπει να οριστεί σε όλες τις γλώσσες. Δέχεται σαν παράμετρο (%s) τον κωδικό ενοικίασης. Αν δεν οριστεί τότε υπάρχει προεπιλεγμένη τιμή μόνο για Αγγλικά (en) `New Rental - %s`.

=== Από
Η διεύθυνση από την οποία θα φαίνεται ότι έχει σταλθεί το e-mail.

=== Προς
Η διεύθυνση που θα λαμβάνει τα e-mail της συγκεκριμένης κατηγορίας.

=== Αποστολή αντιγράφου

Αν θα πάρει αντίγραφο του e-mail της ενοικίασης ο πελάτης ή όχι. Προεπιλεγμένη τιμή `Ναι`.

== Φόρμα επικοινωνίας
Τα e-mails που στέλνονται από τη σελίδα επικοινωνίας του site.

=== Θέμα
Το θέμα του e-mail. Είναι πολυγλωσσικό πεδίο οπότε πρέπει να οριστεί σε όλες τις γλώσσες. Δέχεται σαν παράμετρο (%s) το e-mail που έχει συμπληρώσει ο χρήστης στη φόρμα. Αν δεν οριστεί τότε υπάρχει προεπιλεγμένη τιμή μόνο για Αγγλικά (en) `New Contact - %s`.

=== Από
Η διεύθυνση από την οποία θα φαίνεται ότι έχει σταλθεί το e-mail.

=== Προς
Η διεύθυνση που θα λαμβάνει τα e-mail της συγκεκριμένης κατηγορίας.

=== Αποστολή αντιγράφου
Αν θα πάρει αντίγραφο του e-mail της επικοινωνίας ο πελάτης ή όχι. Προεπιλεγμένη τιμή `Όχι`.

== Φόρμα προσφοράς
Τα e-mails που στέλνονται έπειτα από αίτημα του πελάη για να λάβει προσφορά για κάποιο όχημα.

=== Θέμα
Το θέμα του e-mail. Είναι πολυγλωσσικό πεδίο οπότε πρέπει να οριστεί σε όλες τις γλώσσες. Δέχεται σαν παράμετρο (%s) το e-mail που έχει συμπληρώσει ο χρήστης στη φόρμα. Αν δεν οριστεί τότε υπάρχει προεπιλεγμένη τιμή μόνο για Αγγλικά (en) `New Quote - %s`.

=== Από
Η διεύθυνση από την οποία θα φαίνεται ότι έχει σταλθεί το e-mail.

=== Προς
Η διεύθυνση που θα λαμβάνει τα e-mail της συγκεκριμένης κατηγορίας.

=== Αποστολή αντιγράφου
Αν θα πάρει αντίγραφο του e-mail της προσφοράς ο πελάτης ή όχι. Προεπιλεγμένη τιμή `Όχι`.