= Ρυθμίσεις Συστήματος

== Γενικές

===  Γλώσσες
Οι κωδικοί των γλωσσών που υποστηρίζονται διαχωρισμένοι με κόμμα. Ο πρώτος κωδικός που δίνεται θεωρείται η προεπιλεγμένη γλώσσα του συστήματος.

Οι κωδικοί βασίζονται στο πρότυπο `https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes[ISO 639-1,window=_blank]`.

Αν δεν ορίσουμε κάποια τιμή τότε χρησιμοποιείται ο κωδικός `en`.

.Παράδειγμα, ο κωδικός el (Ελληνικά) θα είναι η προεπιλεγμένη γλώσσα.
----
el,en,es
----

=== Πρότυπο κωδικού ενοικίασης

Το πρότυπο από το οποίο παράγεται ο κωδικός μιας ενοικίασης σε μορφή https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/util/regex/Pattern.html[regular expression,window=_blank].

Αν δεν ορίσουμε κάποια τιμή τότε χρησιμοποιείται το πρότυπο `CR-[A-Z]\{6}-[0-9]\{8}`. +

Με αυτό το πρότυπο έχουμε τρία τμήματα, διαχωρισμένα με παύλα (-). Το πρώτο τμήμα του κωδικού θα ξεκινάει πάντα με `CR`. Το δεύτερο τμήμα θα αποτελείται από 6 κεφαλαίους χαρακτήρες του λατινικού αλφάβητου και το τελευταίο τμήμα από 8 αριθμούς.

.Παράδειγμα παραγόμενου κωδικού.
----
CR-IAMPAO-03021908
----

[CAUTION]
====
Υπάρχει κανόνας για τους χαρακτήρες που πρέπει να έχει ένας κωδικός ενοικίασης.

Πρέπει να είναι έγκυρος σύμφωνα με το regular expression `^[A-Z][A-Z0-9_-]*$`.

* Να αρχίζει με ένα χαρακτήρα του λατινικού αλφαβήτου.
* Να ακολουθείται από χαρακτήρες του λατινικού αλφαβήτου, αριθμούς, καθώς και τους χαρακτήρες παύλα ( - ) και κάτω παύλα ( _ ).
* Όλοι οι χαρακτήρες να είναι κεφαλαίοι.
====

== Έξτρα Ώρες
Έξτρα ώρες υπάρχουν σε μια ενοικίαση όταν η ώρα παράδοσης του οχήματος είναι μεταγενέστερη της ώρας παραλαβής.

=== Τύπος χρέωσης
Όταν υπάρχουν έξτρα ώρες υπάρχουν δύο τύποι χρέωσης.

Επιπλέον ημέρα (WHOLE_DAY):: Ορίζεται ένα όριο δωρεάν ωρών όπου δε γίνεται επιπλέον χρέωση. Αν οι επιπλέον ώρες ξεπερνούν (>) αυτό το όριο τότε υπολογίζεται μια επιπλέον ημέρα στο σύνολο της κράτησης.

Ποσοστιαία (PERCENTAGE):: Ορίζεται ένα ποσοστό χρέωσης για τις επιπλέον ώρες επί της τιμής της ημέρας. Εάν το κόστος των επιπλέον ωρών ξεπεράσει την τιμή ημέρας, τότε προστίθεται μια ακόμα ημέρα στο σύνολο της κράτησης και δε χρεώνονται επιπλέον ώρες.

Αν δεν ορίσουμε κάποιο τύπο χρέωσης τότε ο προεπιλεγμένος είναι η `Επιπλέον ημέρα (WHOLE_DAY)`.

=== Τιμή

Ανάλογα αν ο τύπος χρέωσης είναι `WHOLE_DAY` ή `PERCENTAGE`, η τιμή συμβολίζει τις δωρεάν ώρες ή το ποσοστό χρέωσης αντίστοιχα.

Αν δεν ορίσουμε κάποια τιμή τότε η προεπιλεγμένη τιμή είναι 0. Οπότε ανάλογα με τον τύπο χρέωσης σημαίνει ότι δεν υπάρχουν δωρεάν έξτρα ώρες ή το ποσοστό χρέωσης είναι 0%.

== Νυχτερινές Ώρες
Ορίζεται ένα διάστημα ωρών και ένα σταθερό κόστος χρέωσης για παραλαβή και παράδοση του οχήματος εντός αυτού του διαστήματος.

Τα όρια του διαστήματος συνυπολογίζονται. Δηλαδή αν το διάστημα των νυχτερινών ωρών είναι 22:00-07:00 τότε αν ο πελάτης επιλέξει τα όρια του διαστήματος (22:00 ή 07:00) τότε θα επιβαρυνθεί με το κόστος των νυχτερινών ωρών.

=== Ώρα Έναρξης

Η ώρα που θέλουμε να ξεκινάει το διάστημα των νυχτερινών ωρών. Αν δεν οριστεί τότε δεν υπάρχει διάστημα.

=== Ώρα λήξης

Η ώρα που θέλουμε να τελειώνει το διάστημα των νυχτερινών ωρών. Αν δεν οριστεί τότε δεν υπάρχει διάστημα.

=== Κόστος

Το σταθερό κόστος χρέωσης για το διάστημα των νυχτερινών ωρών. Αν δεν ορίσουμε κάποιο κόστος, το προεπιλεγμένο είναι 0.00€, οπότε δεν υπάρχει χρέωση.

== Τιμολόγηση

== Όρια