= Ρυθμίσεις Συστήματος

== Γενικές

===  Γλώσσες
Οι κωδικοί των γλωσσών που υποστηρίζονται διαχωρισμένοι με κόμμα. Ο πρώτος κωδικός που δίνεται θεωρείται η προεπιλεγμένη γλώσσα του συστήματος.

Οι κωδικοί βασίζονται στο πρότυπο https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes[ISO 639-1,window=_blank].

Αν δεν ορίσουμε κάποια τιμή τότε χρησιμοποιείται ο κωδικός `en`.

.Παράδειγμα, ο κωδικός el (Ελληνικά) θα είναι η προεπιλεγμένη γλώσσα.
----
el,en,es
----

=== Πρότυπο κωδικού ενοικίασης

Το πρότυπο από το οποίο παράγεται ο κωδικός μιας ενοικίασης σε μορφή https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/util/regex/Pattern.html[regular expression,window=_blank].

Αν δεν ορίσουμε κάποια τιμή τότε χρησιμοποιείται το πρότυπο `CR-[A-Z]\{6}-[0-9]\{8}`. +
Με αυτό το πρότυπο έχουμε τρία τμήματα, διαχωρισμένα με παύλα (-). Το πρώτο τμήμα του κωδικού θα ξεκινάει πάντα με `CR`. Το δεύτερο τμήμα θα αποτελείται από 6 κεφαλαίους χαρακτήρες του λατινικού αλφάβητου και το τελευταίο τμήμα από 8 αριθμούς.

.Παράδειγμα παραγόμενου κωδικού.
----
CR-IAMPAO-03021908
----

[CAUTION]
====
Υπάρχει κανόνας για τους χαρακτήρες που πρέπει να έχει ένας κωδικός ενοικίασης.

Πρέπει να είναι έγκυρος σύμφωνα με το regular expression `^[A-Z][A-Z0-9_-]*$`.

* Να αρχίζει με ένα χαρακτήρα του λατινικού αλφαβήτου.
* Να ακολουθείται από χαρακτήρες του λατινικού αλφαβήτου, αριθμούς, καθώς και τους χαρακτήρες παύλα ( - ) και κάτω παύλα ( _ ).
* Όλοι οι χαρακτήρες να είναι κεφαλαίοι.
====

== Έξτρα Ώρες

== Νυχτερινές Ώρες

== Τιμολόγηση

== Όρια