= Ρυθμίσεις Συστήματος

== Γενικές

===  Γλώσσες
Οι κωδικοί των γλωσσών που υποστηρίζονται διαχωρισμένοι με κόμμα. Ο πρώτος κωδικός που δίνεται θεωρείται η προεπιλεγμένη γλώσσα του συστήματος.

Οι κωδικοί βασίζονται στο πρότυπο https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes[ISO 639-1,window=_blank].

Αν δεν ορίσουμε κάποια τιμή τότε χρησιμοποιείται ο κωδικός `en`.

.Παράδειγμα, ο κωδικός el (Ελληνικά) θα είναι η προεπιλεγμένη γλώσσα.
----
el,en,es
----

=== Πρότυπο κωδικού ενοικίασης

Το πρότυπο από το οποίο παράγεται ο κωδικός μιας κράτησης σε μορφή https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/util/regex/Pattern.html[regular expression,window=_blank].

Αν δεν ορίσουμε κάποια τιμή τότε χρησιμοποιείται το πρότυπο `CR-[A-Z]\{6}-[0-9]\{8}`. +
Με αυτό το πρότυπο έχουμε τρία τμήματα, διαχωρισμένα με παύλα (-). Το πρώτο τμήμα του κωδικού θα ξεκινάει πάντα με `CR`. Το δεύτερο τμήμα θα αποτελείται από 6 κεφαλαίους χαρακτήρες του λατινικού αλφάβητου και το τελευταίο τμήμα από 8 αριθμούς.

.Παράδειγμα παραγόμενου κωδικού.
----
CR-IAMPAO-03021908
----

== Έξτρα Ώρες

== Νυχτερινές Ώρες

== Τιμολόγηση

== Όρια