= Καταγραφή Συμβάντων (Logging)

Η παρακολούθηση και καταγραφή των συμβάντων (logs) που σχετίζονται με το backoffice πραγματοποιείται μέσω του συστήματος Graylog.

Το https://graylog.org/[Graylog,window=_blank] αποτελεί μια ισχυρή πλατφόρμα για τη συλλογή, ανάλυση και διαχείριση logs, προσφέροντας τη δυνατότητα να εντοπίζονται γρήγορα προβλήματα, να παρακολουθείται η λειτουργία του συστήματος και να διασφαλίζεται η κανονική του λειτουργία.

== Ρυθμίσεις

[options="autowidth,header",cols="m,,a"]
|===
|Όνομα|Προεπιλογή|Περιγραφή
|LOG_PROTO|udp|Το πρωτόκολλο του input που έχει στηθεί στο Graylog.
|LOG_HOSTNAME|127.0.0.1|Το όνομα του domain ή η IP που τρέχει η υπηρεσία του Graylog.
|LOG_PORT|12201|Η πόρτα που τρέχει η υπηρεσία του Graylog.
3+s|Πρόσθετα πεδία αναγνώρισης
|LOG_APP_CTX|localhost|Το context για το οποία τρέχει η εφαρμογή π.χ. _mycarrental.gr_.
|LOG_APP_ENV|dev|Το περιβάλλον κάτω από το οποίο τρέχει η εφαρμογή π.χ. _production_.
|LOG_APP_SVC|CarRental-Backoffice|Το αναγνωριστικό όνομα της εφαρμογής.
|===

NOTE: Οι ρυθμίσεις δίνονται σαν environment variables.