= Αναφορές και Πρότυπα Email

Το σύστημα στέλνει τριών ειδών mails:

* Από τη φόρμα επικοινωνίας (contact).
* Από τη φόρμα προσφοράς (quote).
* Για μια ενοικίαση (rental).

Χρησιμοποιείται το πρόσθετο https://www.jmix.io/marketplace/reports/["Reports/Αναφορές",window=_blank] του Jmix, για τη δημιουργία των κειμένων των mails, καθώς και της επισυναπτόμενης απόδειξης για το mail της ενοικίασης.

Τα πρότυπα (templates) που χρησιμοποιούνται είναι γραμμένα σε https://freemarker.apache.org/[Apache FreeMarker] μόνο για την Αγγλική γλώσσα (en). Για κάθε γλώσσα που θέλουμε να υποστηρίζει το {app-front} πρέπει να δημιουργηθούν τα αντίστοιχα πρότυπα της γλώσσας.

Κάθε πρότυπο έχει κωδικό με επίθεμα τον κωδικό της γλώσσας, για παράδειγμα _mail_en_. Για κάθε νέα γλώσσα θα πρέπει να δημιουργείται το πρότυπο για τη γλώσσα και στον κωδικό θα χρησιμοποιούμε το επίθεμα της γλώσσας, για παράδειγμα _mail_es_ αν η νέα γλώσσα είναι τα Ισπανικά.

NOTE: Οι υποστηριζόμενες γλώσσες ορίζονται στη σχετική xref:admin/settings-system.adoc#locales[ρύθμιση συστήματος].

NOTE: Για τις ρυθμίσεις της κάθε κατηγορίας email θα βρείτε πληροφορίες στη σχετική ενότητα xref:admin/settings-email.adoc[].

== Mail επικοινωνίας

Το mail επικοινωνίας χρησιμοποιεί την αναφορά `Contact Form` και έχει ένα πρότυπο με κωδικό `contact_mail_en`.

Το πρότυπο χρησιμοποιείται για τη δημιουργία του κειμένου του mail και δέχεται μία παράμετρο με όνομα `form` και είναι τύπου `ContactFormDto`.

.ContactFormDto.java
[,java]
----
include::example$ContactFormDto.java[]
----

== Mail προσφοράς

Το mail προσφοράς χρησιμοποιεί την αναφορά `Quote Form` και έχει ένα πρότυπο με κωδικό `quote_mail_en`.

Το πρότυπο χρησιμοποιείται για τη δημιουργία του κειμένου του mail και δέχεται μία παράμετρο με όνομα `form` και είναι τύπου `QuoteFormDto`.

.QuoteFormDto.java
[,java]
----
include::example$QuoteFormDto.java[]
----

== Mail ενοικίασης

Το mail ενοικίασης χρησιμοποιεί την αναφορά `Rental` και έχει δύο πρότυπα. Το πρότυπο με κωδικό `rental_mail_en` που χρησιμοποιείται για τη δημιουργία του κειμένου του mail και το πρότυπο με κωδικό `rental_attach_en` που χρησιμοποιείται για τη δημιουργία της επισυναπτόμενης απόδειξης.

Τα πρότυπα δέχονται μια παράμετρο με όνομα `form` και είναι τύπου `Rental`.

[tabs]
======
Rental::
+
.Rental.java
[,java]
----
include::example$Rental.java[]
----

Customer::
+
.Customer.java
[,java]
----
include::example$Customer.java[]
----

PickDropDetail::
+
.PickDropDetail.java
[,java]
----
include::example$PickDropDetail.java[]
----

RentalExtra::
+
.RentalExtra.java
[,java]
----
include::example$RentalExtra.java[]
----
======