:nofooter:
:experimental: true
:icons: font
:imagesdir: images
:sectnums:

== Τιμές

Οι τιμές πάνε ως εξής

[%autowidth]
|===
|Price|Calculation|Notes

a| `Rental Basic Price`
a| &nbsp; `Vehicle Total Price` +
+ `Pickup Location Cost` +
+ `DropOff Location Cost` +
+ `Pickup Night Hours Cost` +
+ `DropOff Night Hours Cost` +
+ `Insurance Cost` +
+ `Extras Cost`
a| το `Vehicle Total Price` περιλαμβάνει extra hours & discounts

a|`Coupon Discount`
a|`Rental Basic Price` * `Coupon percent`
a|Tο ποσοστό του κουπονιού που έρχεται από το API είναι δια 100

a|`Payment Cost`
a| Fixed:: Τότε είναι του fee του payment method

Percentage:: (`Rental Basic Price` - `Coupon Discount`) * fee
a|Στην περίπτωση που είναι percentage το fee που έρχεται από το API είναι δια 100

a|`Rental Total Price`
a|&nbsp; `Rental Basic Price` +
-`Coupon Discount` +
+`Payment Cost`
a|
|===

<<<

== Τρόποι πληρωμής

NOTE: Ακολουθεί τι ισχύει για τους τρόπου πληρωμής. Περιγράφω μόνο αυτούς που είχε το παλιό σύστημα για οποιοδήποτε καινούριο θα γίνει ανάλογο setup.

Υπάρχουν οι εξής τρόποι πληρωμής

* PayPal (online)
* Πιστωτική/Χρεωστική κάρτα (online)
* Πληρωμή κατά την παραλαβή (offline)
* Κατάθεση σε τραπεζικό λογαριασμό (offline)

Για κάθε τρόπο πληρωμής υπάρχει η δυνατότητα να οριστεί μια επιβάρυνση είτε σαν fixed ποσό, είτε σαν ποσοστό επί της συνολικής κράτησης.

Για τις online πληρωμές υπάρχει η δυνατότητα ο πελάτης να μην πληρώσει όλο το ποσό, αλλά μέρος αυτού (προκαταβολή) και το υπόλοιπο και το υπόλοιπο κατά την παραλαβή του οχήματος. Η προκαταβολή ορίζεται ποσοστιαία είτε γενικά, είτε για κάθε τρόπο πληρωμής ξεχωριστά. Αν έχουν οριστεί και τα δύο τότε υπερισχύει το ποσοστό που έχει οριστεί στον τρόπο πληρωμής. Αν δεν έχει οριστεί κάποιο ποσοστό είτε γενικό είτε ειδικό, τότε δε δίνεται η δυνατότητα της προκαταβολής και ο πελάτης πρέπει να πληρώσει όλο το ποσό.

Για τον τρόπο πληρωμής Πληρωμή κατά την παραλαβή υπάρχει η δυνατότητα να ορίσουμε ότι ο πελάτης θα πληρώσει ένα ποσό σαν προκαταβολή μέσω της πιστωτικής/χρεωστικής κάρτας.