= image:logo.svg[width=100]
:description: Τεχνικές προδιαγραφές
:author: Μπαριάμης Παναγιώτης <panos@netmechanics.gr>
:version-label: Έκδοση
:revnumber: 1.0
:revdate: 2024-10-10
:organization: Netmechanics S.A.
:nofooter:
:experimental: true
:icons: font
:imagesdir: images
:toc: left
:toc-title: Πίνακας Περιεχομένων
:toclevels: 3
:stylesheet: fedora.css
:source-highlighter: highlight.js
:sectnums:
:example-caption: Παράδειγμα
:table-caption: Παράδειγμα

<<<

== Vocabulary
Site:: Το σύστημα που χρησιμοποιεί ο τελικός πελάτης που θέλει να κάνει μια κράτηση.
Admin:: Το σύστημα που χρησιμοποιεί ο πελάτης της Netmechanics για να διαχειρίζεται το περιεχόμενο του.

== Γενικές Δυνατότητες
// rentacar.minimumReservationDuration
* Ορισμός ελάχιστης διάρκειας κράτησης (σε ημέρες).
// rentacar.reservationSoonestTime
* Ορισμός χρονικού ορίου μετά το οποίο μπορεί να γίνει κράτηση (σε ώρες).
// rentacar.nightHours.cost
// rentacar.nightHours.startAt
// rentacar.nightHours.endAt
* Ορισμός χρονικού διαστήματος (νυχτερινές ώρες), όπου υπάρχει επιβάρυνση στο κόστος της κράτησης, αν η παραλαβή ή η παράδοση του οχήματος είναι μέσα σε αυτό.
// rentacar.time.intervals
* Ορισμός των διαστημάτων της ώρας στο time picker (σε λεπτά) π.χ. Ανά, 15 ή 30
// rentacar.extraHoursType
// rentacar.extraHoursValue
* Χρέωση σε επίπεδο ωρών (έξτρα ώρες), όταν η ώρα παράδοσης του οχήματος είναι μεταγενέστερη της ώρας παραλαβής.
// rentacar.roundingScale
* Στρογγυλοποίηση τιμών στο κοντινότερο δεκαδικό.
// rentacar.vat.included
// rentacar.vat
* Τιμές με ΦΠΑ ή όχι
// rentacar.age.min
// rentacar.age.mαχ
* Ορισμός διαστήματος ηλικίας που μπορεί να έχει ο οδηγός.

<<<

== Κύριες Οντότητες
include::diagrams/uml_class_diagram.adoc[]

<<<

=== Locations
Χρήση:

* Σαν επιλογές Pickup και DropOff, στη φόρμα αναζήτησης οχημάτων στο site.
* Σαν επιλογές για τα unavailable dates ενός vehicle group, για να ορίσουμε αν το group θα είναι μη διαθέσιμο γενικά ή για συγκεκριμένες τοποθεσίες.
* Σαν επιλογές για το minimum duration ενός season. Δηλαδή για να ορίσουμε αν το season θα έχει minimum duration για συγκεκριμένες τοποθεσίες.

Δυνατότητες:

* Ορισμός μια τοποθεσίας ως προεπιλεγμένης στη φόρμα αναζήτησης οχημάτων στο site.
* Ορισμός σαν hotel ή airport, ώστε να συμπληρώνεται υποχρεωτικά ο αριθμός δωματίου ή ο αριθμός πτήσης αντίστοιχα στη φόρμα κράτησης του site.
* Ορισμός pickup κόστους για την τοποθεσία.
* Ορισμός dropOff κόστους για την τοποθεσία.
* Ομαδοποίηση τοποθεσιών για καλύτερη εμφάνιση στο site.
* Ορισμός χρονικού περιθωρίου μετά το οποίο μπορεί να γίνει κράτηση για τη συγκεκριμένη τοποθεσία.
* Ορισμός γεωγραφικού σημείου (lat/lng), για σύνδεση με το Google Maps/Geo API.
* Απενεργοποίηση.

=== Seasons
Χρονικά διαστήματα ανεξάρτητα από το έτος, τα οποία χρησιμοποιούνται σε συνδυασμό με τα vehicle groups, για να ορίσουν το κόστος κράτησης.

Πρέπει να καλύπτουν όλο το ημερολογιακό έτος, διαφορετικά θα υπάρχουν κενά διαστήματα όπου δε θα είναι εφικτή η χρέωση.

Δυνατότητες:

* Δε χρειάζονται τροποποίηση ανά έτος καθώς είναι ανεξάρτητα αυτού.
* Ορισμός ελάχιστης διάρκειας κράτησης για συγκεκριμένη σεζόν ή και για συγκεκριμένη τοποθεσία.

<<<

=== Vehicle Groups
Χρήση:

* Τα vehicle κατηγοριοποιούνται με βάση τα groups.
* Απο την κατηγοριοποίηση αυτή προκύπτουν οι τιμές για μια κράτηση βάση του seasonality.
* Σε συνδυασμό με τα extras για να οριστεί διαφορετική τιμή του extra για το group.
* Σε συνδυασμό με τα insurances για να οριστεί διαφορετική τιμή του insurance για το group.
* Σε συνδυασμό με τα discounts για να οριστεί το discount μόνο σε συγκεκριμένα groups.

Δυνατότητες:

* Εισαγωγή τιμών ανά ημέρα κράτησης (max 30).
* Ρύθμιση από settings πλήθους ημερών κοστολόγησης. Κρατήσεις μεγαλύτερης διάρκειας κοστολογούνται ανά ημέρα όσο το κόστος της τελευταίας ημέρας.
* Ορισμός διαστημάτων μη διαθεσιμότητας (unavailability) ή και για συγκεκριμένη τοποθεσία.
* Ορισμός τιμής/ημέρα, μόνο για θέμα προβολής στο site.
* Απενεργοποίηση.

=== Vehicles
Χρήση:

* Εμφάνιση στη σελίδα "Στόλος" στο site.
* Προς ενοικίαση.

Δυνατότητες.

* Ορισμού σε κάποιο vehicle group ώστε να βγαίνει η τιμή ενοικίασης στους ανα περίοδο.
* Χαρακτηρισμός μέσω tag για προώθηση στο site.
* Ορισμού inventory για όλα τα φυσικά οχήματα που διατίθενται.
* Απενεργοποίηση.

<<<

=== Extras
Χρήση:

* Ορισμός σαν επιπλέον εξοπλισμός ή υπηρεσία που επιλέγεται κατά τη διάρκεια της διαδικασίας της κράτησης στο site.

Δυνατότητες:

* Ορισμός κόστους ανα ημέρα κράτησης ή ανα περίοδο κράτησης.
* Ορισμός διαφορετικού κόστους ανα vehicle group.
* Ορισμού σειρά εμφάνισης στο site.
* Απενεργοποίηση.

=== Insurances
Χρήση:

* Επιλέγεται κατά τη διάρκεια της διαδικασίας της κράτησης στο site.

Δυνατότητες:

* Ορισμός κόστους ανά ημέρα (fixed) ή ποσοστιαίο ανα περίοδο κράτησης
* Ορισμός διαφορετικού κόστους ανα vehicle group.
* Ορισμού σειρά εμφάνισης στο site.
* Απενεργοποίηση.

=== Discounts
Χρήση:

* Εφαρμόζονται αυτόματα κατά τη διάρκεια της κράτησης, εφόσον ισχύουν οι κανόνες των discounts.

Δυνατότητες:

* Ορισμός διαφορετικού τύπου εκπτώσεων (Early Booking, Per Rental, Date Range), όπου ανάλογα εφαρμόζεται και η έκπτωση.
* Ορισμός των εκπτώσεων μόνο σε συγκεκριμένα vehicle groups.
* Απενεργοποίηση.

<<<

=== Coupons
Χρήση:

* Εφαρμόζουν έκπτωση βάση ποσοστού επί της συνολικής τιμής.
* Εφαρμόζονται manually από τον πελάτη εφόσον έχει τον κωδικό του κουπονιού

Δυνατότητες:

* Ορισμού χρονικού διαστήματος για το οποίο ισχύει το κουπόνι.
* Ορισμού χρονικού διαστήματος μέσα στο οποίο πρέπει να είναι η pickup date της κράτησης για να ισχύει το κουπόνι.
* Ορισμός των κουπονιών μόνο σε συγκεκριμένα vehicle groups.
* Απενεργοποίηση.

<<<

== Logic
include::diagrams/rental_activity_diagram.adoc[]

<<<

=== Διαθεσιμότητα Οχημάτων
Ένα όχημα θεωρείται *ενεργό* όταν το ίδιο το όχημα είναι ενεργό αλλά και το γκρουπ που ανήκει είναι ενεργό.

Τόσο στη λίστα του στόλου όσο και στη λίστα των αποτελεσμάτων της αναζήτησης εμφανίζονται *ΜΟΝΟ* ενεργά αυτοκίνητα.

Όταν ένας πελάτης επιλέξει ένα όχημα για να κάνει κράτηση, γίνεται επιπλέον έλεγχος για το αν υπάρχει διαθεσιμότητα του οχήματος ελέγχοντας στο inventory αυτού (status = Available).

Αν δεν υπάρχει ενημερώνεται σχετικά, διαφορετικά προχωράει σε δέσμευση του οχήματος (σε επίπεδο inventory), για συγκεκριμένο χρονικό διάστημα. Αν παρέλθει το διάστημα αυτό χωρίς να έχει ολοκληρωθεί η κράτηση τότε το όχημα αποδεσμεύεται και η διαδικασία της κράτησης ξεκινάει από την αρχή.

=== Χρέωση κράτησης
Η χρέωση μιας κράτησης «στρογγυλοποιείται» σε επίπεδο ημέρας. Δηλαδή, αν η ώρα παράδοσης είναι νωρίτερα απο την ώρα παραλαβής, η χρέωση γίνεται σαν να είχαμε ώρα παράδοσης ίδια με αυτή της παραλαβής, ανεξάρτητα αν ο πελάτης επιστρέψει το όχημα νωρίτερα.

.Χρέωση κράτησης
[%autowidth]
|===
s|Ημ/νία Παραλαβής|10/10/2024 22:00
s|Ημ/νία Παράδοσης|14/10/2024 00:15
s|Ημερολογιακή διάρκεια κράτησης|3 ημέρες 2 ώρες 15 λεπτά
s|Χρεώσιμη διάρκεια κράτησης|4 ημέρες
|===

=== Soonest time
Ορίζεται το ελάχιστο διάστημα (σε ώρες) πριν απο το οποίο *ΔΕΝ* επιτρέπεται στo πελάτη να κάνει κράτηση, με βάση την τωρινή ημ/νία και ώρα. Το διάστημα αυτό ορίζεται είτε σε κάθε τοποθεσία ξεχωριστά είτε global για το σύστημα.

.Παράδειγμα Soonest time
[%autowidth]
|===
s|Τωρινή Ημ/νία και Ώρα|01/10/2024 13:00
s|Soonest time|3 ώρες
s|Επιτρεπόμενη κράτηση από|01/10/2024 16:00 και μετά
|===

=== Νυχτερινές ώρες
Ορίζεται ένα διάστημα ωρών και ένα fixed κόστος χρέωσης για παραλαβή και παράδοση του οχήματος εντός αυτού του διαστήματος.

Τα όρια του διαστήματος συνυπολογίζονται. Δηλαδή αν το διάστημα των νυχτερινών ωρών είναι 22:00-07:00 τότε αν ο πελάτης επιλέξει τα όρια του διαστήματος (22:00 ή 07:00) τότε θα επιβαρυνθεί με το κόστος των νυχτερινών ωρών.

Σε περιπτώσεις όπου έχουμε αλλαγή ημέρας (+1) για σύνολο current time + soonest time, και η πρώτη διαθέσιμη ώρα της επόμενης ημέρας είναι πρωινή τότε ορίζεται η default ώρα (12:00) και απενεργοποιούνται τα απαραίτητα διαστήματα ώρας τα οποία είναι μικρότερα του current time + soonest time.

.Παράδειγμα Soonest time, με αλλαγή ημέρας
[%autowidth]
|===
s|Τωρινή Ημ/νία και Ώρα|01/10/2024 15:00
s|Soonest time|12 ώρες
s|Επιτρεπόμενη κράτηση από|02/10/2024 04:00 και μετά (επιλεγμένη ώρα 12:00)
|===

NOTE: Θα πρέπει στα πεδία time picker της φόρμας αναζήτησης στο site, να απενεργοποιούνται οι αντίστοιχες επιλογές ώρας.

=== Έξτρα ώρες
Έξτρα ώρες υπάρχουν όταν η ώρα παράδοσης του οχήματος είναι μεταγενέστερη της ώρας παραλαβής. Στην περίπτωση αυτή υπάρχουν δύο τρόποι χρέωσης:

WHOLE_DAY::
Ορίζεται ένα όριο δωρεάν ωρών όπου δε γίνεται επιπλέον χρέωση. Αν οι επιπλέον ώρες ξεπερνούν (>) αυτό το όριο τότε υπολογίζεται μια επιπλέον ημέρα στο σύνολο της κράτησης.
+
.WHOLE_DAY - Χρέωση έξτρα ωρών σαν μία επιπλέον ημέρα
[%autowidth]
|===
s|Ημ/νία Παραλαβής|10/10/2024 12:00
s|Ημ/νία Παράδοσης|13/10/2024 17:00
s|Ημερολογιακή διάρκεια κράτησης|3 ημέρες 5 ώρες
s|Όριο δωρεάν ωρών|4
s|Έξτρα ώρες |5 (περισσότερες του ορίου)&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
s|Χρεώσιμη διάρκεια κράτησης|4 ημέρες
|===
+
.WHOLE_DAY - Μη χρέωση έξτρα ωρών
[%autowidth]
|===
s|Ημ/νία Παραλαβής|10/10/2024 12:00
s|Ημ/νία Παράδοσης|13/10/2024 15:30
s|Ημερολογιακή διάρκεια κράτησης|3 ημέρες 3 ώρες 30 λεπτά
s|Όριο δωρεάν ωρών|4
s|Έξτρα ώρες |3.5 (λιγότερες ή ίσες του ορίου)
s|Χρεώσιμη διάρκεια κράτησης|3 ημέρες
|===

PERCENTAGE::
Ορίζεται ένα ποσοστό χρέωσης για τις επιπλέον ώρες επί της τιμής της ημέρας. Εάν το κόστος των επιπλέον ωρών ξεπεράσει την τιμή ημέρας, τότε προστίθεται μια ακόμα ημέρα στο σύνολο της κράτησης και δε χρεώνονται επιπλέον ώρες.
+
.PERCENTAGE - Χρέωση έξτρα ωρών με ποσοστό
[%autowidth]
|===
s|Ημ/νία Παραλαβής|10/10/2024 12:00
s|Ημ/νία Παράδοσης|13/10/2024 15:30
s|Ημερολογιακή διάρκεια κράτησης|3 ημέρες 3 ώρες 30 λεπτά
s|Ποσοστό χρέωσης|15% (0.15)
s|Έξτρα ώρες |3.5
s|Τιμή ημέρας |25.00€
2+|
s|Κόστος έξτρα ωρών|13.125€ => 25.00 * 0.15 * 3.5
s|Χρεώσιμη διάρκεια κράτησης|3 ημέρες 3 ώρες 30 λεπτά
|===
+
.PERCENTAGE - Χρέωση έξτρα ωρών με ποσοστό, χρέωση μία ημέρας
[%autowidth]
|===
s|Ημ/νία Παραλαβής|10/10/2024 12:00
s|Ημ/νία Παράδοσης|13/10/2024 19:30
s|Ημερολογιακή διάρκεια κράτησης|3 ημέρες 7 ώρες 30 λεπτά
s|Ποσοστό χρέωσης|15% (0.15)
s|Έξτρα ώρες |7.5
s|Τιμή ημέρας |25.00€
2+|
s|Κόστος έξτρα ωρών|28.125€ => 25.00 * 0.15 * 7.5
s|Χρεώσιμη διάρκεια κράτησης|4 ημέρες (καθώς το κόστος των επιπλέον ωρών ξεπερνάει την τιμή ημέρας)
|===

=== Εκπτωτικά Κουπόνια
Ορίζονται κουπόνια με ποσοστό έκπτωσης στο σύνολο του κόστους της κράτησης. Τα κουπόνια χρησιμοποιούνται από τους πελάτες κατά τη διαδικασία της κράτησης εφόσον έχουν τον μοναδικό κωδικό του κουπονιού.

Τα κουπόνια υποστηρίζουν ημ/νία έναρξης και λήξης ισχύος, οπότε ακόμα και αν ένας πελάτης έχει έναν κωδικό κουπονιού, δε θα πάρει την έκπτωση αν το κουπόνι δεν έχει ξεκινήσει να ισχύει ή αν έχει λήξει.

Υποστηρίζουν επιπλέον τη δυνατότητα να ορίσουμε διάστημα μέσα στο οποίο θα ισχύει η κράτηση (ημ/νία παραλαβής και παράδοσης), για να δούμε αν ισχύει το κουπόνι ή όχι.

Τέλος, ένα κουπόνι μπορεί να ισχύει για όλα τα οχήματα ή μόνο για κάποια επιλεγμένα γκρουπ.

.Παράδειγμα εφαρμογής κουπονιού
[%autowidth]
|===
s|Ημ/νία έναρξης|01/10/2024
s|Ημ/νία λήξης|31/10/2024
s|Ημ/νία έναρξης κράτησης|01/01/2025
s|Ημ/νία λήξης κράτησης|31/03/2025

2+s|
s|1η Περίπτωση|Ο πελάτης κάνει κράτηση πρίν της 01/10/2024 ή μετά 31/10/2024. Το κουπόνι *δεν* ισχύει καθώς η κράτηση έγινε έκτος του διαστήματος που ορίζουν η ημ/νία έναρξης και λήξης.
2+s|
s|2η Περίπτωση|Ο πελάτης κάνει κράτηση μέσα στο διάστημα 01/10/2024 και 31/10/2024. Με ημερομηνία παραλαβής του οχήματος 15/04/2025 και παράδοσης 20/04/2025. Το κουπόνι *δεν* ισχύει καθώς η κράτηση έγινε έκτος του διαστήματος που ορίζουν η ημ/νία έναρξης και λήξης της κράτησης.
2+s|
s|3η Περίπτωση|Ο πελάτης κάνει κράτηση μέσα στο διάστημα 01/10/2024 και 31/10/2024. Με ημερομηνία παραλαβής του οχήματος 02/02/2025 και παράδοσης 10/02/2025. Το κουπόνι *ισχύει* καθώς η κράτηση έγινε εντός του διαστήματος που ορίζουν η ημ/νία έναρξης και λήξης της κράτησης.
2+a|
NOTE: Στους παραπάνω συνδυασμούς μπορούμε να προσθέσουμε και συγκεκριμένα γκρουπ οχημάτων όπου ελέγχονται επιπλέον των διαστημάτων για το αν θα ισχύει το κουπόνι.
|===

=== Extras
Ορίζονται επιπλέον υπηρεσίες ή εξοπλισμός (extras) τα οποία μπορεί να δηλώσει ο πελάτης ότι θέλει να περιλαμβάνονται στην κράτηση του και έχουν επιπλέον fixed κόστος για την κράτηση. Το κόστος του extra μπορεί να είναι ανα ημέρα ή ανα κράτηση.

Αν κάποιο από τα extras που θα δημιουργηθούν δεν οριστεί συγκεκριμένα σε κάποιο γκρούπ οχημάτων τότε θα είναι διαθέσιμο σε όλα τα γκρούπ, διαφορετικά θα είναι διαθέσιμο *μόνο* στα γκρουπ που έχει οριστεί. Υπάρχει η δυνατότητα να οριστεί κόστος για κάθε γκρουπ ξεχωριστά, διαφορετικά χρησιμοποιείται το γενικό κόστος που έχει οριστεί στο extra.

.Παράδειγμα υπολογισμού extras
[%autowidth]
|===
s|Baby Seat| 1.00€ / ημέρα
s|Additional Driver | 15.00€ / κράτηση
s|Ημέρες κράτησης|10
s|Τιμή ημέρας|20.00€
2+|
s|Συνολικό κόστος κράτησης|45.00€ => 20.00 + (1.00 * 10) + 15.00
|===

=== Εκπτώσεις
Μια έκπτωση μπορεί να ισχύει για όλα τα οχήματα ή μόνο για ένα συγκεκριμένο γκρουπ οχημάτων.

Υπάρχουν 2 τύποι εκπτώσεων:

[upperalpha]
. Εκπτώσεις που εφαρμόζονται στο σύνολο της κράτησης.
.. *Early booking:* πόσο νωρίς έχει γίνει η κράτηση, σε σχέση με την ημ/νία παραλαβής.
.. *Rental duration:* ανάλογα τη διάρκεια της κράτησης για ένα επιλεγμένο διάστημα.
. Εκπτώσεις που εφαρμόζονται σε κάποιες ημέρες της κράτησης.
.. *Date Range:* Συγκεκριμένο διάστημα που θα ισχύει η έκπτωση.

Σε μια κράτηση μπορεί να εφαρμοστεί μόνο μια έκπτωση τύπου Α. Εφαρμόζεται αυτή που έχει το μεγαλύτερο ποσοστό έκπτωσης.

Σε μια κράτηση μπορεί να εφαρμοστεί μόνο μια έκπτωση τύπου B για κάθε ημέρα κράτησης. Εφαρμόζεται αυτή που έχει το μεγαλύτερο ποσοστό έκπτωσης.

Αν υπάρχουν 2 εκπτώσεις ίδιου τύπου, μια γενική και μια για ένα συγκεκριμένο γκρουπ, έχει προτεραιότητα αυτή του γκρουπ, ανεξαρτήτως του ποσοστού έκπτωσης.

Μπορούν να εφαρμοστούν περισσότερες από μια εκπτώσεις τύπου B σε μια κράτηση, εφόσον δεν εφαρμόζονται στις ίδιες ημέρες.

.Παράδειγμα εφαρμογής εκπτώσεων τύπου Β
[%autowidth]
|===
3+s|Εκπτώσεις τύπου Β&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
s|Από s|Έως s|Ποσοστό έκπτωσης
|01/04|15/04|10%
|10/04|30/04|5%

3+s|Διάστημα κράτησης
2+s|Από 1+s|Έως
2+|05/04 1+|10/05

3+s|Εφαρμογή εκπτώσεων
s|Από s|Έως s|Ποσοστό έκπτωσης
|05/04|15/04|10%
|16/04|30/04|5%
|01/05|10/05|Χωρίς έκπτωση
|===

<<<

Το συνολικό ποσό της έκπτωσης προκύπτει, υπολογίζοντας την κάθε έκπτωση ξεχωριστά και αθροίζοντας τα ποσά που προκύπτουν.

.Παράδειγμα υπολογισμού των εκπτώσεων
[%autowidth]
|===
s|Έκπτωση Τύπου Α|8% (0.08)
s|Έκπτωση Τύπου Β|10% (0.10) (ισχύει για 2 ημέρες στο διάστημα της κράτησης)
s|Ημέρες κράτησης|10
s|Τιμή ημέρας|20.00€
2+|
s|Ποσό έκπτωσης Α|16.00€ => 20.00 * 0.08 * 10
s|Ποσό έκπτωσης B|4.00€ => 20.00 * 0.10 * 2
s|Συνολικό ποσό έκπτωσης|20.00€ => 16.00(Α) + 4.00(Β)
|===

NOTE: Το ποσοστό έκπτωσης που θα εμφανίζεται στο site, είναι το ποσοστό που προκύπτει μεταξύ της αρχικής και τελική τιμής, αφού εφαρμοστούν οι εκπτώσεις.

=== Ασφάλειες
Ορίζουμε διάφορες ασφάλειες με διαφορετικό κόστος η κάθε μία. Μπορούμε να ορίσουμε διαφορετικό κόστος ανα γκρουπ οχημάτων για κάθε ασφάλεια.

Υπάρχουν 2 τρόποι υπολογισμού του κόστους μιας ασφάλειας:

[upperalpha]
. Απόλυτο ποσό για κάθε ημέρα κράτησης (Per Day).
+
.Παράδειγμα υπολογισμού κόστους ασφάλειας τύπου Α.
[%autowidth]
|===
s|Ημέρες κράτησης|10
s|Κόστος ασφάλειας |5.00€ ανά ημέρα
2+|
s|Συνολικό κόστος ασφάλειας|50.00€ => 10 * 5.00&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
|===

. Ποσοστό επί του συνόλου της κράτησης (Per Period).
+
Για τον υπολογισμό του κόστους της ασφάλειας στην περίπτωση λαμβάνουμε υπόψιν
+
* Τη βασική τιμή (πλήθος ημερών * τιμή ημέρας) (ΒΤ)
* Τις εκπτώσεις (Ε)
* Το κόστος έξτρα ωρών (ΚΕΩ)
* Το κόστος νυχτερινών ωρών (ΚΝΝ)
* Ποσοστό της ασφάλειας (ΠΑ)
+
Οπότε το κόστος ασφάλειας προκύπτει ως
+
----
(ΒΤ - Ε + ΚΕΩ + ΚΝΝ) * ΠΑ
----
+
WARNING: Στο κόστος της ασφάλειας δε συνυπολογίζονται οποιαδήποτε άλλα κόστη, όπως το κόστος της τοποθεσίας παραλαβής/παράδοσης, το κόστος των extras, ΦΠΑ, κουπόνια κ.α.
+
.Παράδειγμα υπολογισμού κόστους ασφάλειας τύπου Β.
[%autowidth]
|===
s|Ημέρες κράτησης|10
s|Τιμή ημέρας|20.00€
s|Έκπτωση|10.00€
s|Κόστος έξτρα ωρών|5.00€
s|Κόστος τοποθεσίας παραλαβής|5.00€ (δε συμπεριλαμβάνεται στον υπολογισμό)
s|Ποσοστό ασφάλειας |5% (0.05)
2+|
s|Συνολικό κόστος ασφάλειας|9.75€ => ((10 * 20.00) - 10.00 + 5.00) * 0.05
|===

=== Φ.Π.Α.
Εάν το Φ.Π.Α. δε συμπεριλαμβάνεται στις τιμές που έχουν οριστεί, μπορεί να προστεθεί στο
τέλος. Το Φ.Π.Α. εφαρμόζεται στην τελική τιμή της κράτησης.

Εάν υπάρχει κουπόνι, η έκπτωση του κουπονιού εφαρμόζεται μετά την εφαρμογή του Φ.Π.Α.

=== Στρογγυλοποίηση τιμών
Σε κάθε στάδιο του υπολογισμού της τελικής τιμής, η τιμή θα πρέπει να στρογγυλοποιείται. Η στρογγυλοποίηση μπορεί να γίνεται ανά 0,10€ ανά 0,50€ ή ανά 1.00€.

=== Τρόποι πληρωμής
Υπάρχουν οι εξής τρόποι πληρωμής

* PayPal (online)
* Πιστωτική/Χρεωστική κάρτα (online)
* Πληρωμή κατά την παραλαβή (offline)
* Κατάθεση σε τραπεζικό λογαριασμό (offline)

Για κάθε τρόπο πληρωμής υπάρχει η δυνατότητα να οριστεί μια επιβάρυνση είτε σαν fixed ποσό, είτε σαν ποσοστό επί της συνολικής κράτησης.

Για τις online πληρωμές υπάρχει η δυνατότητα ο πελάτης να μην πληρώσει όλο το ποσό, αλλά μέρος αυτού (προκαταβολή) και το υπόλοιπο κατά την παραλαβή του οχήματος. Η προκαταβολή ορίζεται ποσοστιαία είτε γενικά, είτε για κάθε τρόπο πληρωμής ξεχωριστά. Αν έχουν οριστεί και τα δύο τότε υπερισχύει το ποσοστό που έχει οριστεί στον τρόπο πληρωμής. Αν δεν έχει οριστεί κάποιο ποσοστό είτε γενικό είτε ειδικό, τότε δε δίνεται η δυνατότητα της προκαταβολής και ο πελάτης πρέπει να πληρώσει όλο το ποσό.

Για τον τρόπο πληρωμής _Πληρωμή κατά την παραλαβή_, υπάρχει η δυνατότητα να ορίσουμε ότι ο πελάτης θα πληρώσει ένα ποσό σαν προκαταβολή μέσω της πιστωτικής/χρεωστικής κάρτας.