= Προγραμματισμένες εργασίες

Το σύστημα εκτελεί αυτόματα συγκεκριμένες εργασίες σε προκαθορισμένα χρονικά διαστήματα.

[[release-reserved-vehicles-job]]
== Αποδέσμευση οχημάτων

Η εργασία αυτή αναλαμβάνει να αποδεσμεύσει τα οχήματα (σε επίπεδο πινακίδας), που έχουν δεσμευτεί κατά τη διαδικασία ενοικίασης, εφόσον έχει παρέλθει ο σχετικός χρόνος xref:admin/settings-system.adoc#vehicle-reserved-period[Περίοδος δέσμευσης οχήματος (λεπτά)].

Έχει ρυθμιστεί να εκτελείται αυτόματα κάθε δύο λεπτά.

[,properties]
----
nmcr.release-reserved-vehicles-cron=0 1/2 * ? * *
----

Αν δε θέλουμε να ενεργοποιηθεί αυτόματα η εργασία, αλλά να τη ρυθμίσουμε μέσα από το UI αλλάζουμε, αλλάζουμε το property

.application.properties
[,properties]
----
nmcr.use-default-release-reserved-vehicles-quartz-configuration=false
----

.Java class for the job
----
gr.netmechanics.carrental.job.ReleaseReservedVehiclesJob
----

[[abandoned-rentals-job]]
== Εγκαταλελειμμένες ενοικιάσεις

Η εργασία αυτή αναλαμβάνει να ακυρώσει τις ενοικιάσεις και να αποδεσμεύσει τα οχήματα (σε επίπεδο πινακίδας), που έχουν δεσμευτεί κατά τη διαδικασία ενοικίασης, εφόσον έχει παρέλθει ο σχετικός χρόνος xref:admin/settings-system.adoc#rental-reserved-period[Περίοδος δέσμευσης ενοικίασης (λεπτά)].

Έχει ρυθμιστεί να εκτελείται αυτόματα κάθε τρία λεπτά.

[,properties]
----
nmcr.abandoned-rentals-cron=0 1/3 * ? * *
----

Αν δε θέλουμε να ενεργοποιηθεί αυτόματα η εργασία, αλλά να τη ρυθμίσουμε μέσα από το UI αλλάζουμε, αλλάζουμε το property

.application.properties
[,properties]
----
nmcr.use-default-abandoned-rentals-quartz-configuration=false
----

.Java class for the job
----
gr.netmechanics.carrental.job.AbandonedRentalsJob
----

[[finsish-rentals-job]]
== Ολοκλήρωση ενοικιάσεων

Η εργασία αυτή αναλαμβάνει να χαρακτηρίσει τις ενοικιάσεις σαν ολοκληρωμένες και να αποδεσμεύσει τα οχήματα (σε επίπεδο πινακίδας), που έχουν δεσμευτεί. Ο έλεγχος γίνεται με βάση την ημερομηνία παράδοσης και τηv xref:admin/settings-system.adoc#rental-finished-offset[Χρονική μετατόπιση ολοκλήρωσης ενοικίασης (λεπτά)] που έχει οριστεί.

Έχει ρυθμιστεί να εκτελείται αυτόματα κάθε δέκα λεπτά.

[,properties]
----
nmcr.finish-rentals-cron=0 1/10 * ? * *
----

Αν δε θέλουμε να ενεργοποιηθεί αυτόματα η εργασία, αλλά να τη ρυθμίσουμε μέσα από το UI αλλάζουμε, αλλάζουμε το property

.application.properties
[,properties]
----
nmcr.use-default-finish-rentals-quartz-configuration=false
----

.Java class for the job
----
gr.netmechanics.carrental.job.FinishRentalsJob
----

== Αποστολή Email

Η εργασία αυτή προέρχεται από το πρόσθετο https://www.jmix.io/marketplace/email-sending/["Email Sending",window=_blank] του Jmix. Αναλαμβάνει την αποστολή των email που βρίσκονται στην ουρά.

Έχει ρυθμιστεί να εκτελείται αυτόματα κάθε δύο λεπτά.

[,properties]
----
jmix.email.email-sending-cron=* 0/2 * * * ?
----

NOTE: Για περισσότερες πληροφορίες δείτε την τεκμηρίωση της εργασίας https://docs.jmix.io/jmix/email/configuration.html#email-sending-scheduler["Email Sending Scheduler",window=_blank].

== Καθαρισμός Email

Η εργασία αυτή προέρχεται από το πρόσθετο https://www.jmix.io/marketplace/email-sending/["Email Sending",window=_blank] του Jmix. Αναλαμβάνει τον καθαρισμό των αποθηκευμένων email.

Έχει ρυθμιστεί να εκτελείται κάθε δύο ημέρες.

[,properties]
----
jmix.email.email-cleaning-cron=0 0 0 1/2 * ?
----

NOTE: Για περισσότερες πληροφορίες δείτε την τεκμηρίωση της εργασίας https://docs.jmix.io/jmix/email/configuration.html#email-cleaning-scheduler["Email Cleaning Scheduler",window=_blank].